# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.longest_common_subsequence as module_0


def test_case_0():
    str_0 = "4OEko"
    bytes_0 = b"K!Z-\xb8u>5\xd4\x9c"
    var_0 = module_0.longest_common_subsequence(str_0, bytes_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 4324
    module_0.longest_common_subsequence(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\xed~\xe7L\x95e-\xad\x03d\xa3\xd6\x8b\x88\xe9Q("
    var_0 = module_0.longest_common_subsequence(bytes_0, bytes_0)
    assert var_0 == 17
    var_1 = module_0.longest_common_subsequence(bytes_0, bytes_0)
    assert var_1 == 17
    module_0.longest_common_subsequence(var_1, bytes_0)
