name: Pylint Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Required Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint on the Python files
      run: |
        pylint $(git ls-files '*.py')
